#ifndef _MACH_PLATFORM_H
#define _MACH_PLATFORM_H


#define RPI2_PORTIO_BASE	0x3F000000

/* for UART */
#define UART_BASE RPI2_PORTIO_BASE 

#define EARLY_CONSOLE_BUS	(&early_memory_bus)
#define EARLY_CONSOLE_BASE	UART_BASE
#define EARLY_CONSOLE_MAPPING	MAP_LINEAR

#endif /* _MACH_PLATFORM_H */

