#ifndef _MACH_PLATFORM_H
#define _MACH_PLATFORM_H


// FIXME!!!!!!!
#define RPI2_PORTIO_BASE	0x00000000
#define RPI2_UART_BASE		0x00000000

/* for UART */
#define UART_BASE	RPI2_PORTIO_BASE
#define UART_FREQ	2073600

#define EARLY_CONSOLE_BUS	(&early_memory_bus)
#define EARLY_CONSOLE_BASE	UART_BASE
#define EARLY_CONSOLE_MAPPING	MAP_NONE

#endif /* _MACH_PLATFORM_H */

